export const colors = {
  primary: '#0289e0',
  primaryPressed: '#0277c2',
  primaryLight: '#e0f2fe',
  primaryDisabled: '#e0f2fe',
  secondary: '#f9ac03',
  secondaryPressed: '#d99502',
  secondaryLight: '#fff4d6',
  success: '#22c55e',
  successLight: '#dcfce7',
  error: '#ef4444',
  errorLight: '#fee2e2',
  warning: '#f9ac03',
  warningLight: '#fff4d6',
  background: '#f8fafc',
  surface: '#ffffff',
  surfaceAlt: '#e0f2fe',
  card: '#ffffff',
  border: '#e5e7eb',
  borderStrong: '#0289e0',
  text: '#1a1a1a',
  textMuted: '#374151',
  textOnPrimary: '#1a1a1a',
  textOnSecondary: '#1a1a1a',
  textOnFeedback: '#1a1a1a',
  textInverse: '#ffffff',
} as const;

export type ColorToken = keyof typeof colors;
