/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#0289e0",
        "primary-pressed": "#0277c2",
        "primary-light": "#e0f2fe",
        "primary-disabled": "#e0f2fe",
        secondary: "#f9ac03",
        "secondary-pressed": "#d99502",
        "secondary-light": "#fff4d6",
        success: "#22c55e",
        "success-light": "#dcfce7",
        error: "#ef4444",
        "error-light": "#fee2e2",
        warning: "#f9ac03",
        "warning-light": "#fff4d6",
        background: "#f8fafc",
        surface: "#ffffff",
        "surface-alt": "#e0f2fe",
        card: "#ffffff",
        border: "#e5e7eb",
        "border-strong": "#0289e0",
        text: "#1a1a1a",
        "text-muted": "#374151",
        "text-on-primary": "#1a1a1a",
        "text-on-secondary": "#1a1a1a",
        "text-on-feedback": "#1a1a1a",
      },
      fontFamily: {
        arial: ["Arial"],
      },
      fontSize: {
        xs: 12,
        sm: 14,
        md: 16,
        lg: 18,
        xl: 22,
        "2xl": 28,
      },
      spacing: {
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 24,
        "2xl": 32,
        "3xl": 48,
      },
    },
  },
  plugins: [],
};
